image: Visual Studio 2017

build_script:
  - dotnet restore stage\LibUsbDotNet\LibUsbDotNet.csproj
  - dotnet build stage\LibUsbDotNet\LibUsbDotNet.csproj /p:Configuration=Release
  - dotnet pack stage\LibUsbDotNet\LibUsbDotNet.csproj /p:Configuration=Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppVeyorArtifact stage\LibUsbDotNet\bin\Release\LibUsbDotNet.2.2.9-r$($env:APPVEYOR_BUILD_NUMBER).nupkg